project:
  output-dir: _site

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  hikmah-academic-html:
    toc: true
    number-sections: true
  html:
    toc: true
    number-sections: true

bibliography: references.bib
# csl: path/to/your-style.csl  # 按需指定 CSL 文件
resources:
  - figures/
  - tables/
